# Generated by Django 2.2 on 2019-05-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_comment_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='comment_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='dropdown',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_contents',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
